//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvctest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int S_id { get; set; }
        public string S_name { get; set; }
        public int S_age { get; set; }
        public string S_gender { get; set; }
        public string S_post { get; set; }
        public string S_department { get; set; }
    }
}
